[package]
name = "uclip-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58.0", features = ["Win32_Globalization", "Win32_System_DataExchange", "Win32_System_Memory", "Win32_System_Ole"] }
